In [1]:
import torch

In [11]:
x = torch.zeros(4, 2, 3)
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [18]:
x = torch.ones(2, 3, dtype=torch.float32)
print(x.dtype)

torch.float32


In [19]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [22]:
x

tensor([[0.9749, 0.9615],
        [0.7683, 0.4147]])

In [23]:
y

tensor([[0.8228, 0.6781],
        [0.4610, 0.6499]])

In [20]:
z = x+y

In [21]:
z

tensor([[1.7977, 1.6396],
        [1.2293, 1.0646]])

In [24]:
m = torch.add(x,y)

In [25]:
m

tensor([[1.7977, 1.6396],
        [1.2293, 1.0646]])

In [26]:
y.add_(x)

tensor([[1.7977, 1.6396],
        [1.2293, 1.0646]])

In [27]:
y

tensor([[1.7977, 1.6396],
        [1.2293, 1.0646]])

In [2]:
x = torch.tensor([2,3])

In [3]:
x

tensor([2, 3])

In [4]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [5]:
print(x*y)

tensor([[7.7989e-01, 1.5714e-02],
        [3.2466e-01, 3.6609e-04]])


In [6]:
# slicing operations

In [7]:
x  = torch.rand(5,3)

In [8]:
print(x)

tensor([[0.0398, 0.1456, 0.9850],
        [0.3009, 0.5024, 0.5647],
        [0.9118, 0.6802, 0.1318],
        [0.9559, 0.2372, 0.4179],
        [0.8961, 0.8850, 0.0139]])


In [9]:
print(x[:, 0])

tensor([0.0398, 0.3009, 0.9118, 0.9559, 0.8961])


In [10]:
print(x[1, 1])

tensor(0.5024)


In [1]:
print(x[1, :].item())

NameError: name 'x' is not defined

In [ ]:
t = 